### ISSUE TITLE
host network has no port mapping

### ISSUE THREAD

**Issue by kevinhuang0214** [HuakunShen/wol-web#14]
Thank you for making the app. It works well, but with a little problem at docker setup.
WOL doesn't work in docker's default "bridge" network mode, as far as I know. 
So the provided compose.yml didn't work.
```
services:
  wol:
    image: "huakunshen/wol"
    container_name: wol-web
    ports:
      - "8090:8090"  # this will set the network mode to bridge.
    volumes:
      - wol_data:/app/pb_data
    environment:
      - SUPERUSER_EMAIL=root@example.com
      - SUPERUSER_PASSWORD=changeme
volumes:
  wol_data:
```
Instead I change the yml to the following(it work for me):
```
services:
  wol:
    image: "huakunshen/wol"
    container_name: wol-web
    network_mode: host
    volumes:
      - wol_data:/app/pb_data
    environment:
      - SUPERUSER_EMAIL=root@example.com
      - SUPERUSER_PASSWORD=changeme
volumes:
  wol_data:
```
If possible, could you please make a environment variable to set the port used? Port 8090 on host might have been taken by other application already.
